### ISSUE TITLE
Collect website materials

### ISSUE THREAD

**Issue by jslemmer** [fuzeyu/2020-GPW-L5K1-E#1]

**Comment by jslemmer** [comment]
Please design and upload an ERD here

**Comment by jslemmer** [comment]
Here is my ERD, please give me feedback

@Les1ieLee @18996073359

**Comment by fuzeyu** [comment]
Find some templet for our system，upload links to GitHub to decide which is suitable. And make a final decision today.

**Comment by fuzeyu** [comment]
http://www.cssmoban.com/cssthemes/8216.shtml
This is the user interface template I found, which includes the bus route search function we need. There are also additional pages to search hotels and attractions.

**Comment by 18996073359** [comment]
First of all, I directly searched the chengdu public transport website and saw their interface layout and function design, which is conducive to our later development of our own project design, so that we can better reasonable original and template function.
Site at: http://www.cdgjbus.com/articlelist.aspx? Pid = 130

**Comment by 18996073359** [comment]
Last url link can not open, send you again:
http://www.cdgjbus.com/articlelist.aspx?pid=130

**Comment by buxxuan** [comment]
This is the background template I found. Here's the link to it. http://www.cssmoban.com/cssthemes/9311.shtml

**Comment by buxxuan** [comment]
The nice thing about this template is that there are a lot of table styles

**Comment by Les1ieLee** [comment]
This is the background interface template I found. It has the function of observing some management information of sales and analysis.  https://startbootstrap.com/themes/sb-admin-2/

**Comment by Les1ieLee** [comment]
> This is the background interface template I found. It has the function of observing some management information of sales and analysis. https://startbootstrap.com/themes/sb-admin-2/

The advantage of this template is that there are many table styles. Data can be analyzed intuitively.

**Comment by 18996073359** [comment]
Also looked at some template sites:
Here are some interface design, you can learn from, such as the introduction, pictures, and some customer order selection operations
http://www.cssmoban.com/cssthemes/9273.shtml
http://www.cssmoban.com/cssthemes/8180.shtml
Here is the background management system template I am looking for
http://www.cssmoban.com/cssthemes/7473.shtml
This has the ability to view the order management sales volume, as well as the amount of statistics and other functions
http://www.cssmoban.com/cssthemes/7471.shtml
This has order management, chart statistics and other functions
Can meet the manager can see the list of all tickets sold at a certain date, be able to see a passenger on the bus you ordered list of spend the most money in particular tickets, managers must be able to see a dashboard, and the ratio of the daily income of box-office income, statistical functions such as one of the most popular destination, then we discuss learning, hope to have a better project planning.

**Comment by fuzeyu** [comment]
I think the two back-end systems we're looking for are both very good, and both have corresponding login interfaces. But personally, I prefer the background system of Lessie Lee. Because the overall change is smaller than the background system of buxuan. In addition, the table of the second background system can be paged. When we have a lot of data, we don't have to worry about the long table page. But we can learn from the table style in the system which buxuan is looking for.

**Comment by 18996073359** [comment]
I think the fuzeyu's template has a better home page because it has search start and end functions and a sales page. We can add a map to learn from my template of Chengdu public transport. In the background management, we can use the sb admin2 template for statistics and sales, because this template is relatively perfect.

**Comment by buxxuan** [comment]
> I think the fuzeyu's template has a better home page because it has search start and end functions and a sales page. We can add a map to learn from my template of Chengdu public transport. In the background management, we can use the sb admin2 template for statistics and sales, because this template is relatively perfect.



In addition, we can also borrow the code of other templates, such as the template I found has a good table style, we can learn from it

**Comment by fuzeyu** [comment]
Then we can finalize the template. First, the user interface uses the template I found, and then the background interface uses the template found by Lessie Lee. Tomorrow we are going to make a product backlog, then prioritize product functions.
